# 数据源的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pc12jiang
    url: jdbc:mysql://192.168.8.113:3306/imooc_weixin_sell?rewriteBatchedStatements=true&amp;useUnicode=true&characterEncoding=utf8
  jpa:
    show-sql: true
    
# 服务的配置
server:
  servlet:
    context-path: /sell
  port: 8081
    
    
# Logger的配置方式
#logging:
#  path: /var/log/tomcat/sell  # 日志保存路径(C盘下)
##  file: /var/log/tomcat/sell # 日志文件保存路径(C盘下)
#  pattern:
#    console: "%d -%msg%n" # 配置日志的格式
 

   